FROM python:3.9 AS base
WORKDIR /app

FROM base AS builder
WORKDIR /app
COPY main.py /app
COPY requirements.txt /app/

FROM python:3.9-alpine AS final
WORKDIR /app
COPY --from=builder /app .
COPY  --from=builder /app/requirements.txt .
RUN addgroup -g 2000 app \
    && adduser -u 2000 -G app -s /bin/sh -D app
RUN pip install --no-cache-dir -r requirements.txt
USER app
EXPOSE 5000
ENTRYPOINT ["python"]
CMD ["main.py"]